### ISSUE TITLE
Muti-line notes

### ISSUE THREAD

**Issue by lindenxing** [fatihdumanli/onen0te-cli#1]
This is a very excellent tool, but don't support muti-line notes, do you have a plan that support it?

**Comment by fatihdumanli** [comment]
Hi @lindenxing,

Sorry for the late response. You should be able to take multi-line notes with `nnote new` command as it launches the default editor. 

You should also be able to take multiline **inline** notes by not closing the quotes on the first line.

```
$ nnote new -i "this is my
>first
>multi line
>note"
```

should just be fine.

If you're faced with an issue, can you please elaborate further?

**Comment by lindenxing** [comment]
Thank you very much, of course.
